### ISSUE TITLE
updated to 1.2016.12.115 now the plugin stopped working.

### ISSUE THREAD

**Issue by nzhome** [Innofactor/FetchXMLBuilder#167]
An error occured when trying to display this plugin: An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail.

It was working fine before the update.  and all my other plugins are working fine.  I really need fetchxml builder.   I am never going to update ever again.

**Comment by rappen** [comment]
I understand you will never update again. So was this issue just a way of ventilating frustration or would you like some help to solve the problem? ;)

Which version of XrmToolBox are you running?
What was the action you were trying to perform when the error occured?

**Comment by nzhome** [comment]
XrmToolBox v1.2016.10.2
error occurs from the main xrmtoolbox, when I click the FetchXML builder main icon tile.

**Comment by nzhome** [comment]
I tried again, now I get 

An error occured, when trying to display this plugin. Method not found: 'Void XrmToolBox.Extensibility.PluginControlBase.LogInfo(System.String, System.Object[])'.

I have used this plugin with no issues for the  past 2 years. stupid updates.

**Comment by rappen** [comment]
Ok - what you need is the latest version of XrmToolBox.
They usually go hand in hand with the upgrades, and latest FXB uses features made available in latest XTB.

**Comment by nzhome** [comment]
no, i refuse to update XrmToolBox, all my other plugins will probably stop working. all other plugins are working fine.  can you please fix this issue?

**Comment by rappen** [comment]
I am sorry, but this will not be fixed by me.
As this is open source, you are welcome to supply a pull request if you have suggestions for the code that would allow it to work with older incompatible versions of XrmToolBox without introducing too much overhead. You also have to evaluate which versions of XrmToolBox that should be allowed.
The development of the toolbox and the plugins is an ongoing process, and they will continue to follow each other. Occasionally new bugs are discovered, and then they are fixed based on current versions of the tollbox.
If you are afraid of upgrading, I suggest a simple fail-safe, where you unpack the XrmToolBox zip file to a new folder and run it from there. If you have old connection files that you would like to use, you can just add them using the connection manager in XTB.

**Comment by nzhome** [comment]
fine. I will install "another" copy of xrmtoolbox just for FXB.

**Comment by nzhome** [comment]
why did you close it? I haven't given feedback whether that fixes it or not yet.

**Comment by rappen** [comment]
As I said - I will not implement backward compatibility to any older versions of XrmToolBox.
Please supply a pull request if you want to do it.
FXB works very well with latest XTB, I have no doubt you will get it to work.
And the issue reported here ``Method not found: 'Void XrmToolBox.Extensibility.PluginControlBase.LogInfo(System.String, System.Object[])`` is solved by using current XTB version.

**Comment by nzhome** [comment]
at least it looks like the new version of xrmtoolbox has a self auto updating feature now, it didn't have that before.  

but now I get another error:  the process cannot access the file DLaB.AttributeManager.dll because it is being used by another process.

**Comment by nzhome** [comment]
yep that works, now I have to transfer all my connections over in the crm config file. and FXB settings.. that should take me about an hour to set up again..   thanks for the update :) not.

**Comment by rappen** [comment]
You do not have to use my completely free tool.
That is entirely your own choice. If it consumes more time than you gain from using it - then just don't use it.

And I still don't get it - if that backward compatibility to any arbitrary old version of XrmToolBox is so important - why don't you just implement it? The code is available in this very repository where you are writing your complaints. This is open source!
By the way - you could also follow my suggestion to add the old connection file in the connection manager. Or spend an hour typing them in, but please don't blame me for choosing the manual way.

There is also a vital thing you need to know before assuming that sarcastic tone: I don't make any money for suppying you this tool. I needed it myself so I created it, I thought it wasn't half bad, so I published it for others to use. You however do make money using this tool, by making your work more efficient.
Please remember that if you want to submit new issues for improvement of the tool.

**Comment by nzhome** [comment]
I don't even know how to do a pull request in vusual studio. nor do I know how to merge it back into your code :)  great work on the plugin.  keep up the good work, cheers.

**Comment by nzhome** [comment]
yeah true, opensource never works, because everyone updates their components at different times, and nothing ever works end-end :) just my observation and experiences in 15 different occasions.

**Comment by rappen** [comment]
Hopefully no one is forcing you to use open source tools.
Using strictly MS provided tools is always an option.

With that, I wish you best of luck in your continued MSDyn365 development, whether that be with or without the help of FetchXML Builder.

**Comment by shytikov** [comment]
Wait a moment guys :)

We should not blame Open Source. Without open source we wound stuck in Ice Age. 

Remember closed source IE works `end-end`, but we still prefer Chrome (which is wrapper around Open Source Chromium engine). Node.JS become possible because of open source. C# is open source right now, there are tons and tons of software which is either open source or based on ideas grow up from open source. 

While MS Dynamics CRM is not open source. None of us have control over it. Even more, we cannot control environments in a cloud, that MS provides. We constantly experiencing breaking (and *undocumented*) changes in SDKs, APIs and other unpredictable bummers and bottlenecks.

And still we're able to provide you tools that makes your life easier. Because of community. Because we're passionate about CRM. 

Let's make code, not war :)
