### ISSUE TITLE
Personal views all marked "not customizable"

### ISSUE THREAD

**Issue by mwilsonray** [Innofactor/FetchXMLBuilder#205]
Upgraded to version 1.2018.4.2 and we can no longer edit personal views - they all show up as "not customizable". We are still on CRM 2016 (8.0.0.1088). Is there a way to install the prior version in XrmToolBox until this is fixed?

**Comment by rappen** [comment]
Aouch, missed that one. Fixed in next release, in the mean time you can perform this trick to downgrade FetchXML Builder:

1. Download previous package here: https://www.nuget.org/api/v2/package/Cinteros.Xrm.FetchXmlBuilder/1.2018.2.2
2. Rename file from *.nupkg to *.zip
3. Right-click zip file, select Properties
4. Check "Unblock", click Ok.
5. Open zip file folder ``lib\net452\Plugins``
6. Copy the FetchXML Builder dll file
7. Paste the file into folder ``c:\Users\<username>\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\``
8. Run XrmToolBox.

**Comment by mwilsonray** [comment]
Thanks!
